### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by rinigus** [peterleinchen/harbour-defender#1]
Continuation of https://github.com/nodevel/harbour-defender/issues/10

@peterleinchen, Please suggest which license do you want to have and either set it yourself or, with your approval, I can add license as a part of PR for Chum

**Comment by rinigus** [comment]
Ping: So, which license would you like to set? Would be impossible to push it into Chum without any

**Comment by peterleinchen** [comment]
Hey rinigus, 

To be honest, I do not really care which one. And do not know all the differences of those OSS licensd models.
So what about you propose what you feel appropriate?

Best
PL

On Saturday, 22 January 2022, rinigus wrote:
> Ping: So, which license would you like to set? Would be impossible to push it into Chum without any
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/peterleinchen/harbour-defender/issues/1#issuecomment-1019345959
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***

-- 
Peter Leinchen

Sent from my mobile device

**Comment by rinigus** [comment]
OK, I will add then GPLv3 license as it gives you the most of the protection. If someone will wish to change it to some more relaxed one they can always ask you. But probably it is not needed. 

I will add the license text to PR. Now when I know that it is possible to get it to OSS license, I'll work on improving the build scripts and incorporate it all into one PR

**Comment by peterleinchen** [comment]
Perfect! :)

Thank you very much for your initiative!!!

Regards
Peter

On Sunday, 23 January 2022, rinigus wrote:
> OK, I will add then GPLv3 license as it gives you the most of the protection. If someone will wish to change it to some more relaxed one they can always ask you. But probably it is not needed. 
> 
> I will add the license text to PR. Now when I know that it is possible to get it to OSS license, I'll work on improving the build scripts and incorporate it all into one PR
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/peterleinchen/harbour-defender/issues/1#issuecomment-1019524231
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***

-- 
Peter Leinchen

Sent from my mobile device

**Comment by peterleinchen** [comment]
Perfect! :)

Thank you very much for your initiative and work!!!

Regards
Peter

On Sunday, 23 January 2022, rinigus wrote:
> OK, I will add then GPLv3 license as it gives you the most of the protection. If someone will wish to change it to some more relaxed one they can always ask you. But probably it is not needed. 
> 
> I will add the license text to PR. Now when I know that it is possible to get it to OSS license, I'll work on improving the build scripts and incorporate it all into one PR
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/peterleinchen/harbour-defender/issues/1#issuecomment-1019524231
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***

-- 
Peter Leinchen

Sent from my mobile device
